TODO=muladhara.asy
# TODO=svadhishthana.asy
# TODO=manipura.asy
# TODO=anahata.asy
# TODO=vishuddha.asy
# TODO=ajna.asy
# TODO=sahasrara.asy

all:
	asy --libgs="" -f svg $(TODO)
	# asy  -f pdf $(TODO)
