# TODO=muladhara.asy
# TODO=svadhishthana.asy
# TODO=manipura.asy
# TODO=anahata.asy
# TODO=vishuddha.asy
TODO=ajna.asy
# TODO=sahasrara.asy

all:
	asy --libgs="" -tex xelatex -f svg $(TODO)
	asy --libgs="" -tex xelatex -f pdf $(TODO)
	# asy  -f pdf $(TODO)
