TODO=bowline
TODO=doublebowline
TODO=waterbowline
TODO=spearlashing
TODO=farmersloop
TODO=linemanloop
TODO=harnessloop
TODO=rollinghitch
TODO=abok1763
TODO=abok293294
TODO=abok2124
TODO=abok1050
TODO=abok1245
TODO=abok1720
TODO=abok1841
TODO=abok1402

default:
	/home/ferrario/tex/py/psd/psd2pdf.py -p $(TODO).png
	convert $(TODO)_vect.pdf $(TODO).svg
	rm $(TODO)_vect.pdf
